version: "2"
run:
  go: 1.24
  timeout: 10m
  concurrency: 4
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - errcheck
    - gomodguard
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - reassign
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  exclusions:
    presets:
      - comments
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
